/**
 * market_stream.js
 * Exclusively consumes live scored events generated by realtime_scoring_engine.py / Azure Databricks.
 * ZERO client-side fake loops or synthetic generators.
 */

const MarketStream = (() => {
  let processedEventIds = new Set();
  let latestFeed = [];
  let isBackendLive = false;

  const COIN_NAMES = {
    'BTC': 'Bitcoin',
    'ETH': 'Ethereum',
    'SOL': 'Solana',
    'BNB': 'Binance Coin',
    'XRP': 'Ripple',
    'DOGE': 'Dogecoin',
    'ADA': 'Cardano',
    'DOT': 'Polkadot',
    'AVAX': 'Avalanche',
    'LINK': 'Chainlink',
    'MATIC': 'Polygon',
    'SHIB': 'Shiba Inu',
    'UNI': 'Uniswap',
    'NEAR': 'NEAR Protocol',
    'LTC': 'Litecoin',
    'ATOM': 'Cosmos',
    'ICP': 'Internet Computer',
    'SUI': 'Sui',
    'APT': 'Aptos',
    'TRX': 'TRON'
  };

  const currentPrices = {
    'BTC': { price: 65000.00, change24h: '+0.50', name: 'Bitcoin' },
    'ETH': { price: 3400.00, change24h: '+1.20', name: 'Ethereum' },
    'SOL': { price: 145.00, change24h: '-0.80', name: 'Solana' },
    'BNB': { price: 580.00, change24h: '-0.20', name: 'Binance Coin' },
    'XRP': { price: 0.52, change24h: '+0.30', name: 'Ripple' },
    'ADA': { price: 0.45, change24h: '+0.60', name: 'Cardano' },
    'DOGE': { price: 0.12, change24h: '-1.10', name: 'Dogecoin' },
    'DOT': { price: 7.20, change24h: '+0.80', name: 'Polkadot' },
    'AVAX': { price: 26.50, change24h: '+2.10', name: 'Avalanche' },
    'LINK': { price: 11.80, change24h: '-0.40', name: 'Chainlink' },
    'MATIC': { price: 0.42, change24h: '-1.50', name: 'Polygon' },
    'SHIB': { price: 0.000014, change24h: '+3.20', name: 'Shiba Inu' },
    'UNI': { price: 6.80, change24h: '+0.90', name: 'Uniswap' },
    'NEAR': { price: 4.50, change24h: '+1.70', name: 'NEAR Protocol' },
    'LTC': { price: 64.00, change24h: '-0.60', name: 'Litecoin' },
    'ATOM': { price: 4.60, change24h: '-1.00', name: 'Cosmos' },
    'ICP': { price: 7.90, change24h: '+0.40', name: 'Internet Computer' },
    'SUI': { price: 0.88, change24h: '+4.50', name: 'Sui' },
    'APT': { price: 6.70, change24h: '-2.10', name: 'Aptos' },
    'TRX': { price: 0.15, change24h: '+0.10', name: 'TRON' }
  };

  // Poll real live_feed.jsonl from backend
  async function pollBackendFeed() {
    try {
      const res = await fetch('data/live_feed.jsonl?t=' + Date.now());
      if (res.ok) {
        const text = await res.text();
        const lines = text.trim().split('\n').filter(l => l.length > 0);
        
        if (lines.length > 0) {
          isBackendLive = true;
          const newEvents = [];
          
          lines.forEach(line => {
            try {
              const event = JSON.parse(line);
              if (event.order_id && !processedEventIds.has(event.order_id)) {
                processedEventIds.add(event.order_id);
                newEvents.push(event);
              }
            } catch (e) {}
          });

          if (newEvents.length > 0) {
            latestFeed.push(...newEvents);
          }
        } else {
          isBackendLive = false;
        }
      } else {
        isBackendLive = false;
      }
    } catch (err) {
      isBackendLive = false;
    }
  }

  // Poll backend every 500ms
  setInterval(pollBackendFeed, 500);
  pollBackendFeed();

  function nextOrder() {
    if (latestFeed.length > 0) {
      const raw = latestFeed.shift();
      const cleanSymbol = (raw.symbol || 'BTC').replace('_SIM', '');
      const coinName = COIN_NAMES[cleanSymbol] || raw.coin_name || cleanSymbol;
      const priceVal = parseFloat(raw.price) || 100.0;
      const volVal = parseFloat(raw.volume) || 10.0;

      if (currentPrices[cleanSymbol]) {
        currentPrices[cleanSymbol].price = priceVal;
      }

      return {
        order_id: raw.order_id,
        trader_id: raw.trader_id,
        symbol: cleanSymbol,
        coin_name: coinName,
        order_type: raw.order_type || 'buy',
        order_status: raw.order_status || 'executed',
        price: priceVal,
        volume: volVal,
        timestamp: raw.timestamp || raw.scored_at || new Date().toISOString(),
        is_fraud_label: raw.verdict === 'FRAUD' || raw.is_fraud === true,
        attack_type: raw.fraud_type || 'none',
        risk_score: raw.risk_score || 0.1,
        verdict: raw.verdict || 'SAFE',
        xgb_score: raw.xgb_score || 0.1,
        iso_score: raw.iso_score || 0.1,
        ae_score: raw.ae_score || 0.1,
        volume_spike_ratio: raw.volume_spike_ratio || 1.0,
        cancel_to_trade_ratio: raw.cancel_to_trade_ratio || 0.0,
        orders_per_minute: raw.orders_per_minute || 10,
        buy_sell_imbalance: raw.buy_sell_imbalance || 0.0,
        source: 'Azure / Python Realtime Scoring Engine'
      };
    }
    return null;
  }

  function getPrices() {
    return currentPrices;
  }

  function isConnected() {
    return isBackendLive;
  }

  return {
    nextOrder,
    getPrices,
    isConnected
  };
})();
